[package]
name = "rnfe-desktop"
description = "RNFE no desktop: janela (winit + wgpu), som (cpal), gamepad."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "rnfe-desktop"
path = "src/main.rs"

[dependencies]
rnfe-gui.workspace = true
rnfe-frontend.workspace = true
env_logger = { version = "0.11", default-features = false, features = ["auto-color", "humantime"] }

[lints]
workspace = true
